[build]
  command = "npm run build"
  publish = "out" # لو Next.js عندك بستخدم export, لو SSR ممكن تحذف السطر ده

[build.environment]
  NODE_VERSION = "18.17.1" # نسخة مستقرة من Node
  NPM_VERSION = "10"       # تحديد نسخة npm المناسبة

[[plugins]]
  package = "@netlify/plugin-nextjs"
