[build]
  command = "npm run build"
  publish = "out" # لو مشروعك SSR ممكن تحذف السطر ده

[build.environment]
  NODE_VERSION = "16"
  NPM_VERSION = "10"

[[plugins]]
  package = "@netlify/plugin-nextjs"
